### PR TITLE
Update work_from_work.c - avoid kernel panic

### PR DESCRIPTION
**Pull request by stubbfel**
"fix" kernel panic

### CODE REVIEW

**Comment by cirosantilli** [comment]
Thanks, insmod now works!

But it still panics on rmmod, can you try to fix that before merge?

**Comment by stubbfel** [comment]
sorry i didn't test the rmmod command, but now its work for it and re-insmod

**Comment by cirosantilli** [comment]
Merged as: https://github.com/cirosantilli/linux-kernel-module-cheat/commit/f0b9bb30ea2cc3686e80e71ed3e114557eb60aab , thanks!

Is `flush_workqueue( queue );` required? Worked without it, so I removed in further patch.

**Comment by stubbfel** [comment]
i would say yes, because of work items with long executions or missing cancel calls:

from - [http://www.makelinux.net/ldd3/chp-7-sect-6](http://www.makelinux.net/ldd3/chp-7-sect-6)

> Should you need to cancel a pending workqueue entry, you may call:

>>int cancel_delayed_work(struct work_struct *work);

>The return value is nonzero if the entry was canceled before it began execution. The kernel guarantees that execution of the given entry will not be initiated after a call to cancel_delayed_work. If cancel_delayed_work returns 0, however, the entry may have already been running on a different processor, and might still be running after a call to cancel_delayed_work. **To be absolutely sure that the work function is not running anywhere** in the system after cancel_delayed_work returns 0, **you must follow that call with a call to:

>>void flush_workqueue(struct workqueue_struct *queue);**

>After flush_workqueue returns, no work function submitted prior to the call is running anywhere in the system.

**Comment by cirosantilli** [comment]
OK! I put it back in.

**Pull request closed without merging**
